openapi: 3.2.0
info:
  title: ZeroTierOne Service Peer API
  version: 0.1.0
  description: This API controls the ZeroTier service that runs in the background on your computer.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: http://localhost:9993
  description: Production Server
security:
- ApiKeyAuth: []
tags:
- name: Peer
  description: peer status
paths:
  /peer:
    get:
      tags:
      - Peer
      summary: Get all peers
      operationId: getPeers
      responses:
        '200':
          description: Array of Peer objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Peer'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /peer/{address}:
    get:
      tags:
      - Peer
      summary: Get information about a specific peer by Node ID
      operationId: getPeer
      parameters:
      - name: address
        description: ZeroTier address of the peer to get
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Peer object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Peer'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
components:
  responses:
    UnauthorizedError:
      description: Authorization required.
  schemas:
    Peer:
      type: object
      properties:
        address:
          type: string
          example: 992fcf1db7
        isBonded:
          type: boolean
          example: false
        latency:
          type: integer
          example: 40
        paths:
          type: array
          items:
            type: object
            properties:
              active:
                type: boolean
              address:
                type: string
                example: 195.181.173.159/9993
              expired:
                type: boolean
                example: false
              lastReceive:
                type: integer
                format: int64
                example: 1618955164580
              lastSend:
                type: integer
                format: int64
                example: 1618955164596
              preferred:
                type: boolean
                example: true
              trustedPathId:
                type: integer
                example: 0
        role:
          type: string
          example: LEAF
        version:
          type: string
          example: 1.6.4
        versionMajor:
          type: integer
          example: 1
        versionMinor:
          type: integer
          example: 6
        versionRev:
          type: integer
          example: 4
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-ZT1-Auth
